#!/usr/bin/env python3
"""
add_headers.py — Generate a Cloudflare Pages _headers file for browser caching.

Run before pushing to GitHub. Creates a _headers file in the static site root.

Why this matters:
- Cloudflare Pages default: Cache-Control: public, max-age=0, must-revalidate
  → Every asset request goes to the server to check freshness. Slow repeat loads.
- With _headers: static assets cached 7 days in browser
  → Repeat visitors see instant loads. Significant LCP improvement on return visits.

Safe because:
- HTML files are NOT cached (always fresh)
- Cloudflare CDN handles cache invalidation on each deploy
- 7 days is conservative enough to avoid stale assets for active sites

Usage:
    python3 add_headers.py <static-site-dir>

    # Custom max-age (seconds):
    python3 add_headers.py <static-site-dir> --max-age 86400   # 1 day
    python3 add_headers.py <static-site-dir> --max-age 604800  # 7 days (default)
"""

import argparse
import sys
from pathlib import Path

HEADERS_TEMPLATE = """\
# Cloudflare Pages _headers — browser caching for static assets
# Generated by wp-to-cloudflare skill

# Uploaded images: {max_age_days} days
/wp-content/uploads/*
  Cache-Control: public, max-age={max_age}

# Plugin assets (CSS/JS/fonts): {max_age_days} days
/wp-content/plugins/*
  Cache-Control: public, max-age={max_age}

# Theme assets: {max_age_days} days
/wp-content/themes/*
  Cache-Control: public, max-age={max_age}

# 10web Booster cache (if present): {max_age_days} days
/wp-content/cache/*
  Cache-Control: public, max-age={max_age}

# WordPress core includes: {max_age_days} days
/wp-includes/*
  Cache-Control: public, max-age={max_age}

# HTML pages: no browser cache (always fresh from CDN)
/*.html
  Cache-Control: public, max-age=0, must-revalidate
"""


def main():
    parser = argparse.ArgumentParser(description='Add Cloudflare Pages _headers file')
    parser.add_argument('site_dir', help='Path to static site directory')
    parser.add_argument('--max-age', type=int, default=604800,
                        help='Cache max-age in seconds (default: 604800 = 7 days)')
    parser.add_argument('--overwrite', action='store_true',
                        help='Overwrite existing _headers file')
    args = parser.parse_args()

    site_dir = Path(args.site_dir)
    if not site_dir.exists():
        print(f"ERROR: {site_dir} does not exist")
        sys.exit(1)

    headers_path = site_dir / '_headers'
    if headers_path.exists() and not args.overwrite:
        print(f"_headers already exists. Use --overwrite to replace.")
        sys.exit(0)

    max_age_days = round(args.max_age / 86400, 1)
    content = HEADERS_TEMPLATE.format(
        max_age=args.max_age,
        max_age_days=f"{max_age_days:.0f}" if max_age_days == int(max_age_days) else str(max_age_days)
    )

    headers_path.write_text(content)
    print(f"✅ Created {headers_path}")
    print(f"   Assets cached: {max_age_days:.0f} days")
    print(f"   HTML: no-cache (always fresh)")


if __name__ == '__main__':
    main()
